# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\CMake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\victo_000\Documents\Visual Studio 2015\Projects\EIP---SRV"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\victo_000\Documents\Visual Studio 2015\Projects\EIP---SRV"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	echo >nul && "C:\Program Files (x86)\CMake\bin\cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files (x86)\CMake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\victo_000\Documents\Visual Studio 2015\Projects\EIP---SRV\CMakeFiles" "C:\Users\victo_000\Documents\Visual Studio 2015\Projects\EIP---SRV\CMakeFiles\progress.marks"
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\victo_000\Documents\Visual Studio 2015\Projects\EIP---SRV\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named domothink

# Build rule for target.
domothink: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) domothink
.PHONY : domothink

# fast build rule for target.
domothink\fast:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\build
.PHONY : domothink\fast

src\api\PostgreSQL\src\postgre.obj: src\api\PostgreSQL\src\postgre.cpp.obj

.PHONY : src\api\PostgreSQL\src\postgre.obj

# target to build an object file
src\api\PostgreSQL\src\postgre.cpp.obj:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\api\PostgreSQL\src\postgre.cpp.obj
.PHONY : src\api\PostgreSQL\src\postgre.cpp.obj

src\api\PostgreSQL\src\postgre.i: src\api\PostgreSQL\src\postgre.cpp.i

.PHONY : src\api\PostgreSQL\src\postgre.i

# target to preprocess a source file
src\api\PostgreSQL\src\postgre.cpp.i:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\api\PostgreSQL\src\postgre.cpp.i
.PHONY : src\api\PostgreSQL\src\postgre.cpp.i

src\api\PostgreSQL\src\postgre.s: src\api\PostgreSQL\src\postgre.cpp.s

.PHONY : src\api\PostgreSQL\src\postgre.s

# target to generate assembly for a file
src\api\PostgreSQL\src\postgre.cpp.s:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\api\PostgreSQL\src\postgre.cpp.s
.PHONY : src\api\PostgreSQL\src\postgre.cpp.s

src\exception.obj: src\exception.cpp.obj

.PHONY : src\exception.obj

# target to build an object file
src\exception.cpp.obj:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\exception.cpp.obj
.PHONY : src\exception.cpp.obj

src\exception.i: src\exception.cpp.i

.PHONY : src\exception.i

# target to preprocess a source file
src\exception.cpp.i:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\exception.cpp.i
.PHONY : src\exception.cpp.i

src\exception.s: src\exception.cpp.s

.PHONY : src\exception.s

# target to generate assembly for a file
src\exception.cpp.s:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\exception.cpp.s
.PHONY : src\exception.cpp.s

src\main.obj: src\main.cpp.obj

.PHONY : src\main.obj

# target to build an object file
src\main.cpp.obj:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\main.cpp.obj
.PHONY : src\main.cpp.obj

src\main.i: src\main.cpp.i

.PHONY : src\main.i

# target to preprocess a source file
src\main.cpp.i:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\main.cpp.i
.PHONY : src\main.cpp.i

src\main.s: src\main.cpp.s

.PHONY : src\main.s

# target to generate assembly for a file
src\main.cpp.s:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\main.cpp.s
.PHONY : src\main.cpp.s

src\server.obj: src\server.cpp.obj

.PHONY : src\server.obj

# target to build an object file
src\server.cpp.obj:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\server.cpp.obj
.PHONY : src\server.cpp.obj

src\server.i: src\server.cpp.i

.PHONY : src\server.i

# target to preprocess a source file
src\server.cpp.i:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\server.cpp.i
.PHONY : src\server.cpp.i

src\server.s: src\server.cpp.s

.PHONY : src\server.s

# target to generate assembly for a file
src\server.cpp.s:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\server.cpp.s
.PHONY : src\server.cpp.s

src\utils.obj: src\utils.cpp.obj

.PHONY : src\utils.obj

# target to build an object file
src\utils.cpp.obj:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\utils.cpp.obj
.PHONY : src\utils.cpp.obj

src\utils.i: src\utils.cpp.i

.PHONY : src\utils.i

# target to preprocess a source file
src\utils.cpp.i:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\utils.cpp.i
.PHONY : src\utils.cpp.i

src\utils.s: src\utils.cpp.s

.PHONY : src\utils.s

# target to generate assembly for a file
src\utils.cpp.s:
	$(MAKE) -f CMakeFiles\domothink.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\domothink.dir\src\utils.cpp.s
.PHONY : src\utils.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... domothink
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... src/api/PostgreSQL/src/postgre.obj
	@echo ... src/api/PostgreSQL/src/postgre.i
	@echo ... src/api/PostgreSQL/src/postgre.s
	@echo ... src/exception.obj
	@echo ... src/exception.i
	@echo ... src/exception.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/server.obj
	@echo ... src/server.i
	@echo ... src/server.s
	@echo ... src/utils.obj
	@echo ... src/utils.i
	@echo ... src/utils.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

